### ISSUE TITLE
Failure on creating intermediate cert, 

### ISSUE THREAD

**Issue by GESTIFANOS** [PatWie/yoca#3]
Your Own Certificate Authority
http://github.com/PatWie/yoca
------------------------------------

info :  create intermediate key
What root certificate to use: jd
Please specify a name for your intermediate: jd
Please specify the keysize: 2048
Generating RSA private key, 2048 bit long modulus
.........+++
.....................................................+++
e is 65537 (0x10001)
Enter pass phrase for intermediate_certs/private_keys/jd.key.pem:
Verifying - Enter pass phrase for intermediate_certs/private_keys/jd.key.pem:
info :  check if key intermediate_certs/private_keys/jd.key.pem exists
ok   :  key does exists
info :  create a intermediate cert
Which intermediate key to use: jd
error on line -1 of intermediate/openssl.cnf
140222085523104:error:02001002:system library:fopen:No such file or directory:bss_file.c:169:fopen('intermediate/openssl.cnf','rb')
140222085523104:error:2006D080:BIO routines:BIO_new_file:no such file:bss_file.c:172:
140222085523104:error:0E078072:configuration file routines:DEF_LOAD:no such file:conf_def.c:197:
info :  check if request intermediate_certs/certs/jd.csr.pem exists

error:  certificate does NOT exists --> abort

root@driver:/etc/nginx/ssl1/intermediate_certs# ls
certs  index.txt  private_keys  public_keys  serial
root@driver:/etc/nginx/ssl1/intermediate_certs# ll certs/
total 8
drwxr-xr-x 2 root root 4096 Apr 22 02:31 ./
drwxr-xr-x 5 root root 4096 Apr 22 02:31 ../
root@driver:/etc/nginx/ssl1/intermediate_certs#  ll private_keys/
total 12
drwx------ 2 root root 4096 Apr 22 02:36 ./
drwxr-xr-x 5 root root 4096 Apr 22 02:31 ../
-r-------- 1 root root 1766 Apr 22 02:36 jd.key.pem
root@driver:/etc/nginx/ssl1/intermediate_certs# ll public_keys/
total 8
drwxr-xr-x 2 root root 4096 Apr 22 02:31 ./
drwxr-xr-x 5 root root 4096 Apr 22 02:31 ../
root@driver:/etc/nginx/ssl1/intermediate_certs# ll certs/
total 8
drwxr-xr-x 2 root root 4096 Apr 22 02:31 ./
drwxr-xr-x 5 root root 4096 Apr 22 02:31 ../
root@driver:/etc/nginx/ssl1/intermediate_certs#

**Comment by PatWie** [comment]
You need to setup first the ca.conf, because it will internally count the certificates
